# -*- coding: utf-8 -*-
"""PythonExercises_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AahoXpWesIw57juJAgvtZtbqe80rAlQq

**Kevin Gonzalez**

**Student ID 1908434**

**Artificial Intelligence**

**Tuesday N4**

---
***Program that will convert a decimal number into a binary number.***
"""

decimal_num = int(input("Enter a decimal number: "))
binary_num = bin(decimal_num).replace("0b","")
print("The binary conversion of " + str(decimal_num) + " is " + str(binary_num))

"""1. First we input the decimal number that will be converted.
2. Then we use the built in *bin* function to convert the decimal number into binary. (The .replace is used to eliminate the 0b that is placed when we use the *bin* function) 
3. Finally we print out the results with a string converter so that we can add them up and create a sentence.

---

***Program that make a math pyramid starting from a list of integers.***
"""

number_input = input("Enter a list of numbers, with each one separated by a space: ")
number_list = [int(x) for x in number_input.split()]
print(number_list)
while len(number_list) != 1:
  for i in range(len(number_list)):
    if i == (len(number_list)-1):
      del number_list[i]
    else:
      number_list[i] = (number_list[i+1] + number_list[i])
  print(number_list)

"""1.   First we input a set of numbers in a string.
2.   To convert this string into a list of ints, we use the split function, which will divide the string using the spaces between the numbers.
3. Then, the numbers of the list are added to the one on the right, while the last element of the list is deleted.
4. We print the list with the new values and repeat the process until there is only one element in the list.
"""